version: "3.3"
services:
  frontend_server:
    build: ./Frontend_server
    ports:
      - "8082:8082"
    depends_on:
      - order_server
  order_server:
    build: ./Order_server
    volumes:
      - ./Order_server/data:/data
    depends_on:
      - catalog_server
  catalog_server:
    build: ./Catalog_server
    volumes:
      - ./Catalog_server/data:/data
